version: '3'

services:
 db:
    container_name: lab3
    image: postgres:latest
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: test
 app:
   container_name: lab3
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     PORT:  "8081"
   ports:
      - "8081:8081"