version: '3'

services:
 db:
    container_name: my_lab4_container 
    image: postgres:latest
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: test
 app:
   container_name: lab4
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     PORT:  "8082"
   ports:
      - "8082:8082"