version: '3'

services:
 db:
    image: postgres:latest
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: test
 app:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     PORT:  "8080"
   ports:
      - "8080:8080"